-- AlterEnum (v2.9 C2)
ALTER TYPE "AuditAction" ADD VALUE 'COST_CENTRE_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'COST_CENTRE_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'BUDGET_CREATED';
ALTER TYPE "AuditAction" ADD VALUE 'BUDGET_UPDATED';
ALTER TYPE "AuditAction" ADD VALUE 'BUDGET_COMMITTED';
ALTER TYPE "AuditAction" ADD VALUE 'BUDGET_RELEASED';
ALTER TYPE "AuditAction" ADD VALUE 'PR_CANCELLED';
