-- v2.19: onboarding & account-lifecycle notification events.
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_INVITED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVITE_REMINDER';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'INVITE_EXPIRED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_WELCOME';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_ACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'USER_REACTIVATED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'ROLE_CHANGED';
ALTER TYPE "NotificationType" ADD VALUE IF NOT EXISTS 'PASSWORD_RESET';
